version: '3.3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
  parser:
    build: .
    command: python main.py
    volumes:
      - .:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - db